# NOTE: This Makefile was generated by Claude

# ==============================================================================
# NES Emulator Makefile
# ==============================================================================
#
# Targets:
#   make              Build the main emulator binary (default)
#   make clean        Remove the build directory
#
# Dependencies (install via your package manager):
#   glib-2.0          pkg-config --libs glib-2.0
#   SDL2              (optional — needed once you wire up rendering)
#
# ==============================================================================

# ------------------------------------------------------------------------------
# Directories
# ------------------------------------------------------------------------------

ROOT        := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
SRC_DIR     := $(ROOT)/src
BUILD_DIR   := $(ROOT)/build

# ------------------------------------------------------------------------------
# Toolchain
# ------------------------------------------------------------------------------

CC          := gcc
# TDOD: Add -Werror once the project becomes more stable
CFLAGS      := -std=c11 -Wall -Wextra -Wpedantic \
               -Wno-unused-parameter \
               -g \
               $(shell pkg-config --cflags glib-2.0)
LDFLAGS     := $(shell pkg-config --libs glib-2.0) -lm

# Uncomment when you add SDL2:
# CFLAGS  += $(shell pkg-config --cflags sdl2)
# LDFLAGS += $(shell pkg-config --libs sdl2)

# ------------------------------------------------------------------------------
# Sources — main emulator
# ------------------------------------------------------------------------------

HW_DIR      := $(SRC_DIR)/hw

SRCS        := $(SRC_DIR)/main.c \
               $(HW_DIR)/nes.c \
               $(HW_DIR)/cpu/cpu.c \
               $(HW_DIR)/ppu/ppu.c \
               $(HW_DIR)/apu/apu.c \
               $(HW_DIR)/cartridge/cartridge.c \
               $(HW_DIR)/controller/controller.c

# ------------------------------------------------------------------------------
# Object files (mirrors source tree under build/)
# ------------------------------------------------------------------------------

OBJS        := $(patsubst $(SRC_DIR)/%.c,$(BUILD_DIR)/%.o,$(SRCS))

# ------------------------------------------------------------------------------
# Binary names
# ------------------------------------------------------------------------------

TARGET      := $(BUILD_DIR)/nes

# ------------------------------------------------------------------------------
# Default target
# ------------------------------------------------------------------------------

.PHONY: all
all: $(TARGET)

# ------------------------------------------------------------------------------
# Link
# ------------------------------------------------------------------------------

$(TARGET): $(OBJS)
	@echo "[LD]  $@"
	@$(CC) $(OBJS) -o $@ $(LDFLAGS)

# ------------------------------------------------------------------------------
# Compile — generic rule for all .c files under src/
#
# $(@D) expands to the directory of the target object file, which mirrors the
# source tree under build/.  We create it with mkdir -p before compiling so
# that subdirectories (build/hw/cpu/, build/hw/ppu/, etc.) are created
# automatically without needing explicit rules for each one.
# ------------------------------------------------------------------------------

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(@D)
	@echo "[CC]  $<"
	@$(CC) $(CFLAGS) -I$(SRC_DIR) -c $< -o $@

.PHONY: clean
clean:
	@echo "[RM]  $(BUILD_DIR)"
	@rm -rf $(BUILD_DIR)

# ------------------------------------------------------------------------------
# Automatic dependency tracking
#
# -MMD -MP causes gcc to emit a .d file alongside each .o containing the
# header dependencies discovered during compilation.  Including them here
# means that editing any .h file triggers a rebuild of all .o files that
# include it — without any manual dependency lists.
# ------------------------------------------------------------------------------

CFLAGS      += -MMD -MP
DEPS        := $(OBJS:.o=.d) $(TEST_OBJS:.o=.d)
-include $(DEPS)
