# NOTE: This Makefile was generated by Claude

# ==============================================================================
# NES Emulator Makefile
# ==============================================================================
#
# Build output goes to $(ROOT)/build/
# Sources live under $(ROOT)/src/
#
# Targets:
#   make              Build the main emulator binary (default)
#   make test         Build the nestest CPU validation binary
#   make clean        Remove the build directory
#   make run ROM=x    Build and run the emulator with a ROM
#   make run_test     Build and run nestest, diff against nestest.log
#
# Dependencies (install via your package manager):
#   glib-2.0          pkg-config --libs glib-2.0
#   SDL2              (optional — needed once you wire up rendering)
#
# ==============================================================================

# ------------------------------------------------------------------------------
# Directories
# ------------------------------------------------------------------------------

ROOT        := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
SRC_DIR     := $(ROOT)/src
BUILD_DIR   := $(ROOT)/build

# ------------------------------------------------------------------------------
# Toolchain
# ------------------------------------------------------------------------------

CC          := gcc
# TDOD: Add -Werror once the project becomes more stable
CFLAGS      := -std=c11 -Wall -Wextra -Wpedantic \
               -Wno-unused-parameter \
               -g \
               $(shell pkg-config --cflags glib-2.0)
LDFLAGS     := $(shell pkg-config --libs glib-2.0) -lm

# Uncomment when you add SDL2:
# CFLAGS  += $(shell pkg-config --cflags sdl2)
# LDFLAGS += $(shell pkg-config --libs sdl2)

# ------------------------------------------------------------------------------
# Sources — main emulator
# ------------------------------------------------------------------------------

HW_DIR      := $(SRC_DIR)/hw

SRCS        := $(SRC_DIR)/main.c \
               $(HW_DIR)/nes.c \
               $(HW_DIR)/cpu/cpu.c \
               $(HW_DIR)/ppu/ppu.c \
               $(HW_DIR)/apu/apu.c \
               $(HW_DIR)/rom/rom.c \
               $(HW_DIR)/controller/controller.c

# ------------------------------------------------------------------------------
# Sources — nestest harness
# ------------------------------------------------------------------------------

TEST_SRCS   := $(SRC_DIR)/test_nestest.c \
               $(HW_DIR)/nes.c \
               $(HW_DIR)/bus/bus.c \
               $(HW_DIR)/cpu/cpu.c \
               $(HW_DIR)/ppu/ppu.c \
               $(HW_DIR)/apu/apu.c \
               $(HW_DIR)/rom/rom.c \
               $(HW_DIR)/controller/controller.c

# ------------------------------------------------------------------------------
# Object files (mirrors source tree under build/)
# ------------------------------------------------------------------------------

OBJS        := $(patsubst $(SRC_DIR)/%.c,$(BUILD_DIR)/%.o,$(SRCS))
TEST_OBJS   := $(patsubst $(SRC_DIR)/%.c,$(BUILD_DIR)/%.o,$(TEST_SRCS))

# ------------------------------------------------------------------------------
# Binary names
# ------------------------------------------------------------------------------

TARGET      := $(BUILD_DIR)/nes
TEST_TARGET := $(BUILD_DIR)/nestest

# ------------------------------------------------------------------------------
# Default target
# ------------------------------------------------------------------------------

.PHONY: all
all: $(TARGET)

# ------------------------------------------------------------------------------
# Link
# ------------------------------------------------------------------------------

$(TARGET): $(OBJS)
	@echo "[LD]  $@"
	@$(CC) $(OBJS) -o $@ $(LDFLAGS)

$(TEST_TARGET): $(TEST_OBJS)
	@echo "[LD]  $@"
	@$(CC) $(TEST_OBJS) -o $@ $(LDFLAGS)

# ------------------------------------------------------------------------------
# Compile — generic rule for all .c files under src/
#
# $(@D) expands to the directory of the target object file, which mirrors the
# source tree under build/.  We create it with mkdir -p before compiling so
# that subdirectories (build/hw/cpu/, build/hw/ppu/, etc.) are created
# automatically without needing explicit rules for each one.
# ------------------------------------------------------------------------------

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(@D)
	@echo "[CC]  $<"
	@$(CC) $(CFLAGS) -I$(SRC_DIR) -c $< -o $@

# ------------------------------------------------------------------------------
# Convenience targets
# ------------------------------------------------------------------------------

.PHONY: test
test: $(TEST_TARGET)

.PHONY: run
run: $(TARGET)
ifndef ROM
	$(error ROM is not set. Usage: make run ROM=path/to/game.nes)
endif
	@$(TARGET) $(ROM)

# Runs nestest and diffs against nestest.log (must be in the project root)
.PHONY: run_test
run_test: $(TEST_TARGET)
	@echo "[RUN] nestest"
	@$(TEST_TARGET) > $(BUILD_DIR)/nestest_out.log
	@echo "[DIFF] comparing against nestest.log"
	@diff $(BUILD_DIR)/nestest_out.log $(ROOT)/nestest.log \
		&& echo "PASS — output matches nestest.log" \
		|| echo "FAIL — see diff above"

.PHONY: clean
clean:
	@echo "[RM]  $(BUILD_DIR)"
	@rm -rf $(BUILD_DIR)

# ------------------------------------------------------------------------------
# Automatic dependency tracking
#
# -MMD -MP causes gcc to emit a .d file alongside each .o containing the
# header dependencies discovered during compilation.  Including them here
# means that editing any .h file triggers a rebuild of all .o files that
# include it — without any manual dependency lists.
# ------------------------------------------------------------------------------

CFLAGS      += -MMD -MP
DEPS        := $(OBJS:.o=.d) $(TEST_OBJS:.o=.d)
-include $(DEPS)
